package co.com.pragma.bootcamp.auth.api.mapper;


import co.com.pragma.bootcamp.auth.api.dto.UserRegistrationRequest;
import co.com.pragma.bootcamp.auth.api.dto.UserRegistrationResponse;
import co.com.pragma.bootcamp.auth.model.user.User;

public class UserDtoMapper {
    public static User toUser(UserRegistrationRequest request) {
        return new User(
            null, // Assuming ID is generated by the database
            request.firstName(),
            request.lastName(),
            request.birthDate(),
            request.address(),
            request.phone(),
            request.email(),
            request.baseSalary()
        );
    }

    public static UserRegistrationResponse toUserRegistrationResponse(User user) {
        return new UserRegistrationResponse(
            user.getId(),
            user.getFirstName(),
            user.getLastName(),
            user.getBirthDate(),
            user.getAddress(),
            user.getPhone(),
            user.getEmail(),
            user.getBaseSalary()
        );
    }
}
